### ISSUE TITLE
Значение потребленной мощности в киловатт часах, сбросилось и начало считать заново

### ISSUE THREAD

**Issue by Aleks130699** [vortigont/pzem-edl#1]
{"age":245,"U":200.1,"I":10.79,"P":2104,"W":16976,"hz":50.0,"pF":0.97}
Вчера значение когда подключил esp значение показало 52квч, хотя на прошивке тасмола было 378 квч, сегодня же значение пошло считать заново, при этом достало примерно до 65квч и сбросилось, мое предположение что это проблема может быть в переменной unsigned int у которой значения 0… 65 535

**Comment by Aleks130699** [comment]
Да скорее всего это проблема переполнения переменной, посчитал что 378 квт, это как раз 5 полных раз по 65,5 квт, и остается примерно 50 квт

**Comment by vortigont** [comment]
ОК, понял, похоже проблема вот здесь.
```
        energy  = __builtin_bswap16(*(uint16_t*)&value[REG_ENERGY_L*2])  | __builtin_bswap16(*(uint16_t*)&value[REG_ENERGY_H*2]   << 16);
```
 Сначала нужно делать байт своп, а потом сдвиг, поправлю тогда вечерком.

**Comment by vortigont** [comment]
P.S. хороший у вас расход :)

**Comment by Aleks130699** [comment]
16 бит для этих чисел скорее всего не хватает, как по мне, ну вам лучше знать)

**Comment by vortigont** [comment]
само значение энергии 32 битное, но пзем отдает его как два 16 битных регистра с перевернутым порядком старшего байта. Я ошибочно сдвиг под скобку внёс ) поправил - тестируйте.

**Comment by Aleks130699** [comment]
Проверил, все круто, теперь правильно показывает
