### ISSUE TITLE
loop() not working / Execute own program Code Example.

### ISSUE THREAD

**Issue by Petros144** [vortigont/pzem-edl#10]
Hi @vortigont,

It´s Me again. I had success with the Signale Values, now I tried to add some stuff to loop() and it is not working.

this kind of Programing is new to me, can you give a newbie a example on how to execute my "own" code? with your Library?

Sorry for these kind of questions, but i would love to use ur Library for my projekt.

Thanks in advance.

**Comment by vortigont** [comment]
Hi @Petros144,

`loop()` is not related to the lib code at all, it work asynchronously. So you are free to put anything there.
Just make sure to remove `vTaskDelete(NULL);` if it was left from the example code. Otherwise it will kill loop execution at first run.
