### ISSUE TITLE
Your examples do not compile in Arduino IDE

### ISSUE THREAD

**Issue by todosko** [vortigont/pzem-edl#14]
Swears like this -

In file included from C:\Users\User\Documents\Arduino\libraries\pzem-edl-main\examples\03_MultiplePZEM004\src\main.h:14:0,
                 from C:\Users\User\Documents\Arduino\libraries\pzem-edl-main\examples\03_MultiplePZEM004\src\main.cpp:14:
C:\Users\User\Documents\Arduino\libraries\pzem-edl-main\src/pzem_edl.hpp:18:19: fatal error: LList.h: No such file or directory
compilation terminated.
exit status 1
Compilation error for board ESP32 Dev Module.

What to do?

**Comment by vortigont** [comment]
you need to install this lib [LinkedList](https://github.com/vortigont/LinkedList)
